//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 04:31:58 PM CET 
//


package fr.kben.google.geocode.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressComponentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressComponentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="street_address"/>
 *     &lt;enumeration value="route"/>
 *     &lt;enumeration value="intersection"/>
 *     &lt;enumeration value="political"/>
 *     &lt;enumeration value="country"/>
 *     &lt;enumeration value="administrative_area_level_1"/>
 *     &lt;enumeration value="administrative_area_level_2"/>
 *     &lt;enumeration value="administrative_area_level_3"/>
 *     &lt;enumeration value="colloquial_area"/>
 *     &lt;enumeration value="locality"/>
 *     &lt;enumeration value="sublocality"/>
 *     &lt;enumeration value="neighborhood"/>
 *     &lt;enumeration value="premise"/>
 *     &lt;enumeration value="subpremise"/>
 *     &lt;enumeration value="postal_code"/>
 *     &lt;enumeration value="natural_feature"/>
 *     &lt;enumeration value="airport"/>
 *     &lt;enumeration value="park"/>
 *     &lt;enumeration value="point_of_interest"/>
 *     &lt;enumeration value="post_box"/>
 *     &lt;enumeration value="street_number"/>
 *     &lt;enumeration value="floor"/>
 *     &lt;enumeration value="room"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AddressComponentType")
@XmlEnum
public enum AddressComponentType {

    @XmlEnumValue("street_address")
    STREET_ADDRESS("street_address"),
    @XmlEnumValue("route")
    ROUTE("route"),
    @XmlEnumValue("intersection")
    INTERSECTION("intersection"),
    @XmlEnumValue("political")
    POLITICAL("political"),
    @XmlEnumValue("country")
    COUNTRY("country"),
    @XmlEnumValue("administrative_area_level_1")
    ADMINISTRATIVE_AREA_LEVEL_1("administrative_area_level_1"),
    @XmlEnumValue("administrative_area_level_2")
    ADMINISTRATIVE_AREA_LEVEL_2("administrative_area_level_2"),
    @XmlEnumValue("administrative_area_level_3")
    ADMINISTRATIVE_AREA_LEVEL_3("administrative_area_level_3"),
    @XmlEnumValue("colloquial_area")
    COLLOQUIAL_AREA("colloquial_area"),
    @XmlEnumValue("locality")
    LOCALITY("locality"),
    @XmlEnumValue("sublocality")
    SUBLOCALITY("sublocality"),
    @XmlEnumValue("neighborhood")
    NEIGHBORHOOD("neighborhood"),
    @XmlEnumValue("premise")
    PREMISE("premise"),
    @XmlEnumValue("subpremise")
    SUBPREMISE("subpremise"),
    @XmlEnumValue("postal_code")
    POSTAL_CODE("postal_code"),
    @XmlEnumValue("natural_feature")
    NATURAL_FEATURE("natural_feature"),
    @XmlEnumValue("airport")
    AIRPORT("airport"),
    @XmlEnumValue("park")
    PARK("park"),
    @XmlEnumValue("point_of_interest")
    POINT_OF_INTEREST("point_of_interest"),
    @XmlEnumValue("post_box")
    POST_BOX("post_box"),
    @XmlEnumValue("street_number")
    STREET_NUMBER("street_number"),
    @XmlEnumValue("floor")
    FLOOR("floor"),
    @XmlEnumValue("room")
    ROOM("room");
    private final String value;

    AddressComponentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddressComponentType fromValue(String v) {
        for (AddressComponentType c: AddressComponentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
