//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 04:31:58 PM CET 
//


package fr.kben.google.geocode.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.kben.google.geocode.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeocodeResponse_QNAME = new QName("http://www.kben.org/google-geocode", "GeocodeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.kben.google.geocode.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link GeocodeResponse }
     * 
     */
    public GeocodeResponse createGeocodeResponse() {
        return new GeocodeResponse();
    }

    /**
     * Create an instance of {@link Geometry }
     * 
     */
    public Geometry createGeometry() {
        return new Geometry();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link AddressComponent }
     * 
     */
    public AddressComponent createAddressComponent() {
        return new AddressComponent();
    }

    /**
     * Create an instance of {@link Viewport }
     * 
     */
    public Viewport createViewport() {
        return new Viewport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeocodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kben.org/google-geocode", name = "GeocodeResponse")
    public JAXBElement<GeocodeResponse> createGeocodeResponse(GeocodeResponse value) {
        return new JAXBElement<GeocodeResponse>(_GeocodeResponse_QNAME, GeocodeResponse.class, null, value);
    }

}
